### ISSUE TITLE
statically linked binaries

### ISSUE THREAD

**Issue by pmenzel** [EvolBioInf/andi#11]
Hi,

would it be possible to also have statically linked binaries available for download?

That would help to have the newest version included in bioconda, since there is a [problem](https://github.com/bioconda/bioconda-recipes/pull/21578) with the gsl version requirement on their build environment. 
In this case, it would be easier to have the official static binary used by bioconda.

thanks!

**Comment by kloetzl** [comment]
Hang on. Looking into it.

**Comment by kloetzl** [comment]
I'll keep this open to remind me that there is an issue with old compilers/versions of C. https://github.com/bioconda/bioconda-recipes/pull/21578
