### ISSUE TITLE
no configure

### ISSUE THREAD

**Issue by crashfrog** [EvolBioInf/andi#2]
./configure not actually present in repo. autoconf didn't run, maybe?

**Comment by kloetzl** [comment]
This is intentional, as I do not want to put automatically generated files under version control. Please run `autoreconf -i` after cloning (assuming you have the autotools installed). For some autotools version you will have to do `autoreconf -i -Im4` instead.

**Comment by crashfrog** [comment]
That's fine, but you might then consider an update to your installation instructions, which do mention running "configure" from the cloned directory. 

The dependency on autoreconf isn't currently documented.

**Comment by kloetzl** [comment]
> The dependency on autoreconf isn't currently documented.

I disagree. Both the [Readme](https://github.com/EvolBioInf/andi/blob/master/README.md) and the [manual](https://github.com/EvolBioInf/andi/blob/master/docs/manual/andi-manual.pdf) mention `autoreconf` when installing from git. As I'd like to keep the readme small, that won't change. But I could add another paragraph in the manual about dependencies.

**Comment by crashfrog** [comment]
Sorry, I guess I missed it the first time through. That's my bad - I should have read more carefully.

Compilation from source *did* require glib, though (libglib2.0-dev was what I used.) I know it seems nit-picky but you'd be surprised what isn't present on the sort of minimal Ubuntu install that forms the basis for a lot of Docker images.

**Comment by kloetzl** [comment]
That's strange. I use glib2, but only for unit tests. Thus a simple `./configure` without `--enable-unit-tests` should work just fine. If the issue persist, even with an explicit `./configure --disable-unit-tests`, let me know. Then its probably a bug in the `configure.ac`.

**Comment by kloetzl** [comment]
I am closing this as *invalid*. Feel free to open other issues/PRs if the problems persist.
