### ISSUE TITLE
Problems upgrading the brew package to 0.9.6.1

### ISSUE THREAD

**Issue by tseemann** [EvolBioInf/andi#5]
Fabian

I've tried to do it : https://github.com/Homebrew/homebrew-science/pull/3305
But having problems with divsufsort.  It seems to find it, but something isn't right.
Does it use `pkgconfig` to discover it?
It seems to work on Linux but not on Mac.

```
checking divsufsort.h usability... no
checking divsufsort.h presence... yes
configure: WARNING: divsufsort.h: present but cannot be compiled
configure: WARNING: divsufsort.h:     check for missing prerequisite headers?
configure: WARNING: divsufsort.h: see the Autoconf documentation
configure: WARNING: divsufsort.h:     section "Present But Cannot Be Compiled"
configure: WARNING: divsufsort.h: proceeding with the compiler's result
checking for divsufsort.h... no
checking for divsufsort in -ldivsufsort... yes
configure: error: Configuration for libdivsufsort failed. Either install libdivsufsort, or use our replacement, psufsort, instead.
	./configure --without-libdivsufsort
The latter may result in longer runtimes.
```

If I disable I still get error here: https://github.com/EvolBioInf/andi/issues/6

**Comment by kloetzl** [comment]
No pkgconf involved, just standard autoconf (`AC_CHECK_HEADERS`). Seems like the headers aren't getting found.

**Comment by kloetzl** [comment]
As far as andi is concerned nothing changed with the way we detect libdivsufsort. I wonder, why its breaking all of a sudden.

**Comment by tseemann** [comment]
I don't seem to have a problem on Linuxbrew, but I do on OSX Brew. Not sure why! 

I've tried letting it auto-detect, I've appended and prepended `CPPFLAGS` and `LDFLAGS` paths etc but I'm stumped.

**Comment by kloetzl** [comment]
Hm. That is curios, to say the least. The libdivsufsort in homebrew is still 2.0.1, right?

**Comment by kloetzl** [comment]
My debugging result so far: libdivsufsort uses some Microsoft extensions in its headers `__declspec(dllexport)`. So one has to add `-fms-extensions` to the flags. Now andi compiles on OS X but still [fails with trap: 5](https://travis-ci.org/EvolBioInf/andi/jobs/108992202).

**Comment by kloetzl** [comment]
I just released [v0.9.6.2](https://github.com/EvolBioInf/andi/releases/tag/v0.9.6.2) which should fix all issues. Or at least, things [build fine](https://travis-ci.org/EvolBioInf/andi/builds/109026711) on TravisCI with OS X now.

**Comment by tseemann** [comment]
Ok, i've added it finally but without libdivsufsort for this release, no time to debug it.

https://github.com/Homebrew/homebrew-science/pull/3305

**Comment by kloetzl** [comment]
Cool, thanks. If you ever want a package in Debian, let me know. :smile:
