### ISSUE TITLE
strcchrnul.c - error: use of undeclared identifier 'NULL'

### ISSUE THREAD

**Issue by tseemann** [EvolBioInf/andi#6]
This occurs on OSX compiler with both GCC and CLANG:

```
clang -DHAVE_CONFIG_H -I. -I../src   -I/usr/local/opt/libdivsufsort/include -I/usr/local/Cellar/gsl/1.16/include  -g -O2 -c -o reallocarray.o reallocarray.c
strchrnul.c:7:14: error: use of undeclared identifier 'NULL'
        return p != NULL ? p : strchr(s, '\0');
```

I'm guessing `NULL` is defined in `stdio.h` or `stdlib.h` and you have no `#include` in that C file.

**Comment by kloetzl** [comment]
That file is never compiled under linux, thus I didn't catch the error. Should be fixed now.
