### ISSUE TITLE
libdivsufsort - compatible with sdsl-lite?

### ISSUE THREAD

**Issue by tseemann** [EvolBioInf/andi#8]
Can we link against the `libdivsufsort` from here?
https://github.com/simongog/sdsl-lite

**Comment by kloetzl** [comment]
I don't know. Does sdsl-lite install libdivsufsort as a dynamic library for the whole system? If so, linking is possible. If it just builds and links libdivsufsort statically, then that is not possible. Can't tell, though, I am not a CMake expert.

**Comment by tseemann** [comment]
As it currently stands, it only creates static libraries:

```
/home/linuxbrew/.linuxbrew/Cellar/sdsl-lite/2.1.1/lib/pkgconfig/libdivsufsort.pc
/home/linuxbrew/.linuxbrew/Cellar/sdsl-lite/2.1.1/lib/pkgconfig/libdivsufsort64.pc
/home/linuxbrew/.linuxbrew/Cellar/sdsl-lite/2.1.1/lib/libdivsufsort.a
/home/linuxbrew/.linuxbrew/Cellar/sdsl-lite/2.1.1/lib/libdivsufsort64.a
```

**Comment by kloetzl** [comment]
libdivsufsort is by Yuta Mori whereas sdsl is by Simon Gog. I don't think they have anything to do with each other.

**Comment by tseemann** [comment]
That's an unfortunate coincidence!

**Comment by kloetzl** [comment]
sdsl should use the system-wide installation of libdivsufsort instead of making its own static build. I am closing this as *won't fix*.
